// miniprogram/pages/post/post.js
const app = getApp();
const request = require('../../utils/request.js');
let time = require('../../utils/util.js');
var countdown = 60;
var urlWechatAcc = app.globalData.url + '/api/content/autoGenerated/wechatAcc';
var urlWechatApplet = app.globalData.url + '/api/content/autoGenerated/wechatApplet';
var urlZhihuAcc = app.globalData.url + '/api/content/autoGenerated/zhihuAcc';
var urlDouyinAcc = app.globalData.url + '/api/content/autoGenerated/douyinAcc';

var token = app.globalData.token;

Page({

    /**
     * 页面的初始数据
     */
    data: {
        StatusBar: app.globalData.StatusBar,
        CustomBar: app.globalData.CustomBar,
        Custom: app.globalData.Custom,
        skin: app.globalData.skin,
        style: app.globalData.highlightStyle,
        hasUserInfo: false,
        canIUse: wx.canIUse('button.open-type.getUserInfo'),
        CommentShow: false,
        ButtonTimer: '', //  按钮定时器
        LastTime: 60,
        CommentSwitch: true,
        commentValue: '',
        currentPage: 0,
        wechatAccList: [],
        wechatAccListHasNext: true,
        wechatAppletList: [],
        wechatAppletListHasNext: true,
        zhiHuAccList: [],
        zhiHuAccListHasNext: true,
        douYinAccList: [],
        douYinListHasNext: true,
        wechatAcc: false,
        wechatApplet: false,
        zhihu: false,
        douyin: false,
        commercialCategory: false,
        categories: [],
        bgColor: 'red'
    },

    /**
     * 生命周期函数--监听页面加载
     */
    onLoad: function (options) {
        var postId = options.postId;
        this.setData({
            postId: postId
        })
        var urlContent = app.globalData.url + '/api/content/posts/' + postId;
        var token = app.globalData.token;
        var params = {};
        //@todo 文章内容网络请求API数据
        request.requestGetApi(urlContent, token, params, this, this.successFunPost, this.failFunPost);

        var urlComments = urlContent + '/comments/list_view';
        //@todo 评论列表网络请求API数据
        request.requestGetApi(urlComments, token, params, this, this.successComment, this.failComment);

        var urlSwitch = app.globalData.url + '/api/content/options/keys/comment_api_enabled';
        //@todo 评论开启按钮网络请求API数据
        request.requestGetApi(urlSwitch, token, params, this, this.successSwitch, this.failSwitch);

        // //@todo tags网络请求API数据
        this.requestTagstData();

        this.setData({
            postTitleImg: app.globalData.postTitleImg,
            postBottomImg: app.globalData.postBottomImg,
        });
    },

    /**
     * 生命周期函数--监听页面初次渲染完成
     */
    onReady: function () {

    },

    /**
     * 生命周期函数--监听页面显示
     */
    onShow: function () {
        var userInfo = wx.getStorageSync('userInfo')
        if (userInfo) {
            this.setData({
                userInfo: userInfo,
                hasUserInfo: true
            })
        } else if (this.data.canIUse) {
            // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
            // 所以此处加入 callback 以防止这种情况
            app.userInfoReadyCallback = res => {
                this.setData({
                    userInfo: res.userInfo,
                    hasUserInfo: true,
                })
            }
        }
    },

    /**
     * 生命周期函数--监听页面隐藏
     */
    onHide: function () {

    },

    /**
     * 生命周期函数--监听页面卸载
     */
    onUnload: function () {

    },

    /**
     * 页面相关事件处理函数--监听用户下拉动作
     */
    onPullDownRefresh: function () {
        console.log("onPullDownRefresh triggered");
    },

    /**
     * 页面上拉触底事件的处理函数
     */
    touchBottom: function () {
        this.setData({
            "currentPage": this.data.currentPage + 1,
        });

        if (this.data.wechatAcc && this.data.wechatAccListHasNext) {
            this.requestWechatAccData();
        } else {
            console.log("no more wechatAcc data");
        }

        if (this.data.wechatApplet && this.data.wechatAppletListHasNext) {
            this.requestWechatAppletData();
        } else {
            console.log("no more wechatApplet data");
        }

        if (this.data.zhihu && this.data.zhiHuAccListHasNext) {
            this.requestZhiHuData();
        } else {
            console.log("no more zhihu data");
        }

        if (this.data.douyin && this.data.douYinListHasNext) {
            this.requestDouYinData();
        } else {
            console.log("no more douyin data");
        }
    },

    /**
     * 获取Tags列表
     */
    requestTagstData: function (e) {
        var urlTags = app.globalData.url + '/api/admin/tags'; //读取首页背景图地址
        var token = app.globalData.token;
        var params = {};
        request.requestGetApi(urlTags, token, params, this, this.successTags, this.failTags);
    },

    /**
     * 成功获取tags列表
     */
    successTags: function (res, selfObj) {
        var that = this;
        if (res.data) {
            for (var item of res.data) {
                if ('小程序首页背景'.indexOf(item.name) > -1) {
                    this.setData({
                        backgroundimgurl: item.thumbnail
                    })
                } else if (('便民工具箱'.indexOf(item.name) > -1) && ('y'.indexOf(item.slug) > -1)) {
                    that.setData({
                        toolBox: true
                    })
                }
            }
        }
    },

    /**
     * 获取tags列表错误
     */
    failTags: function (res, selfObj) {
        console.error('failTags', res)
    },

    /**
     * 用户点击右上角分享
     */
    onShareAppMessage: function () {
        var imageUrl;
        if (this.data.commercialCategory) {
            this.data.postTitle = "[" + this.data.categories[0].name + "]-" + this.data.postTitle;
            imageUrl = this.data.categories[0].thumbnail;
        } else {
            imageUrl = this.data.postThumbnail;
        }

        return {
            title: this.data.postTitle,
            path: '/pages/post/post?postId=' + this.data.postId,
            imageUrl: imageUrl,
        }
    },

    /**
     * 用户点击右上角分享朋友圈
     */
    onShareTimeline: function () {
        var imageUrl;
        if (this.data.commercialCategory) {
            this.data.postTitle = "[" + this.data.categories[0].name + "]-" + this.data.postTitle;
            if ("利明说车频道".indexOf(this.data.categories[0].name) > -1) {
                imageUrl = "https://s2.loli.net/2022/06/30/c6qxzvuSPNCj1ey.png";
            } else {
                imageUrl = 'https://s2.loli.net/2022/06/30/FruqtL7O1xIQBSP.png';
            }
        } else {
            imageUrl = 'https://s2.loli.net/2022/06/30/FruqtL7O1xIQBSP.png';
        }

        return {
            title: this.data.postTitle,
            path: '/pages/post/post?postId=' + this.data.postId,
            imageUrl: imageUrl,
        }
    },

    /**
     * 文章详情请求--接口调用成功处理
     */
    successFunPost: function (res, selfObj) {
        var that = this;
        var createTime = res.data.createTime;
        that.setData({
            postTitle: res.data.title,
            postVisits: res.data.visits,
            postLikes: res.data.likes,
            postUrl: app.globalData.url + res.data.originalContentUrl,
            postContent: res.data.originalContent,
            postDate: time.customFormatTime(createTime, 'Y-M-D'),
            categories: res.data.categories,
            postTags: res.data.tags,
            postThumbnail: res.data.thumbnail,
            commercialCategory: '11'.indexOf(res.data.categoryIds) > -1,
        })

        if (res.data.metas[0]) {
            if ('wechatAcc'.indexOf(res.data.metas[0].key) > -1) {
                that.setData({
                    wechatAcc: true,
                    PageCur: 'wechatAcc',
                    bgColor: 'green'
                })
                this.requestWechatAccData();
            }

            if ('wechatApplet'.indexOf(res.data.metas[0].key) > -1) {
                that.setData({
                    wechatApplet: true,
                    PageCur: 'wechatApplet',
                    bgColor: 'green'
                })
                this.requestWechatAppletData();
            }

            if ('zhihu'.indexOf(res.data.metas[0].key) > -1) {
                that.setData({
                    zhihu: true,
                    PageCur: 'zhihu',
                    bgColor: 'blue'
                })
                this.requestZhiHuData();
            }

            if ('douyin'.indexOf(res.data.metas[0].key) > -1) {
                that.setData({
                    douyin: true,
                    PageCur: 'douyin',
                    bgColor: 'red'
                })
                this.requestDouYinData();
            }
        }
    },

    /**
     * 文章详情请求--接口调用失败处理
     */
    failFunPost: function (res, selfObj) {
        console.error('failFunPosts', res)
    },

    /**
     * 获取知乎列表
     */
    requestZhiHuData: function (e) {
        var params = {
            'page': this.data.currentPage,
            'size': '30'
        };
        request.requestGetApi(urlZhihuAcc, token, params, this, this.successZhiHuPost, this.failZhiHuPost);
    },

    /**
     * 成功获取知乎列表
     */
    successZhiHuPost: function (res, selfObj) {
        var that = this;
        that.setData({
            zhiHuAccList: this.data.zhiHuAccList.concat(res.data.content),
            zhiHuAccListHasNext: res.data.hasNext
        })
    },

    /**
     * 获取知乎列表错误
     */
    failZhiHuPost: function (res, selfObj) {
        console.error('failWechatAppletPost', res)
    },

    /**
     * 获取抖音列表
     */
    requestDouYinData: function (e) {
        var params = {
            'page': this.data.currentPage,
            'size': '30',
            'sort': 'ranking,desc'
        };
        request.requestGetApi(urlDouyinAcc, token, params, this, this.successDouYinPost, this.failDouYinPost);
    },

    /**
     * 成功获取抖音列表
     */
    successDouYinPost: function (res, selfObj) {
        var that = this;
        that.setData({
            douYinAccList: this.data.douYinAccList.concat(res.data.content),
            douYinListHasNext: res.data.hasNext
        })
    },

    /**
     * 获取抖音列表错误
     */
    failDouYinPost: function (res, selfObj) {
        console.error('failWechatAppletPost', res)
    },

    /**
     * 获取小程序列表
     */
    requestWechatAppletData: function (e) {
        var params = {
            'page': this.data.currentPage,
            'size': '30'
        };
        request.requestGetApi(urlWechatApplet, token, params, this, this.successWechatAppletPost, this.failWechatAppletPost);
    },
    /**
     * 成功获取小程序列表
     */

    successWechatAppletPost: function (res, selfObj) {
        var that = this;
        that.setData({
            wechatAppletList: this.data.wechatAppletList.concat(res.data.content),
            wechatAppletListHasNext: res.data.hasNext
        })
    },

    /**
     * 获取小程序列表错误
     */
    failWechatAppletPost: function (res, selfObj) {
        console.error('failWechatAppletPost', res)
    },

    /**
     * 获取公众号列表
     */
    requestWechatAccData: function (e) {
        var params = {
            'page': this.data.currentPage,
            'size': '30'
        };
        request.requestGetApi(urlWechatAcc, token, params, this, this.successWechatPost, this.failWechatPost);
    },

    /**
     * 二维码长按识别
     */
    previewImage: function (e) {
        console.log(e);
        var current = e.currentTarget.id;
        console.log(current);
        wx.previewImage({
                urls: [current],
                current: current,
                showmenu: true
            },
            this.successPreview,
            this.failPreview,
            this.completePreview
        )
    },
    successPreview: function (res, selfObj) {
        console.log('successPreview', res)
    },
    failPreview: function (res, selfObj) {
        console.log('failPreview', res)
    },
    completePreview: function (res, selfObj) {
        console.log('completePreview', res)
    },

    /**
     * 成功获取公众号列表
     */

    successWechatPost: function (res, selfObj) {
        var that = this;
        that.setData({
            wechatAccList: this.data.wechatAccList.concat(res.data.content),
            wechatAccListHasNext: res.data.hasNext
        })
    },

    /**
     * 获取公众号列表错误
     */
    failWechatPost: function (res, selfObj) {
        console.error('failWechatPost', res)
    },

    /**
     * 评论列表请求--接口调用成功处理
     */
    successComment: function (res, selfObj) {
        var that = this;
        console.info(res.data);
        var list = res.data.content;
        if (list.length != 0) {
            for (let i = 0; i < list.length; ++i) {
                list[i].createTime = time.customFormatTime(list[i].createTime, 'Y-M-D  h:m:s');
                list[i].falg = true;
                if (list[i].isAdmin) {
                    list[i].email = '';
                    list[i].authorUrl = 'https://cn.gravatar.com/avatar/3958035fa354403fa9ca3fca36b08068?s=256&d=mm';
                }
            }
            list[list.length - 1].falg = false;
        }
        that.setData({
            commentList: res.data.content,
        })
    },
    /**
     * 评论列表请求--接口调用失败处理
     */
    failComment: function (res, selfObj) {
        console.error('failComment', res)
    },

    /**
     * 评论模块
     */
    Comment: function (e) {
        var content = e.detail.value.replace(/\s+/g, '');
        // console.log(content);
        var that = this;
        that.setData({
            CommentContent: content,
        });
    },

    CommentSubmit: function (e) {
        var that = this;
        if (!that.data.CommentContent) {
            wx.showToast({
                title: '评论内容不能为空！',
                icon: 'none',
                duration: 2000
            })
        } else {
            that.setData({
                CommentShow: true,
            });
            that.data.ButtonTimer = setInterval(function () {
                if (countdown == 0) {
                    that.setData({
                        CommentShow: false,
                    })
                    countdown = 60;
                    clearInterval(that.data.ButtonTimer);
                    return;
                } else {
                    that.setData({
                        LastTime: countdown
                    });
                    countdown--;
                }
            }, 1000)
            wx.cloud.callFunction({
                name: 'msg_sec_check',
                data: {
                    content: that.data.CommentContent
                }
            }).then(ckres => {
                if (ckres.result.errCode == 0) {
                    var urlPostList = app.globalData.url + '/api/content/posts/comments';
                    var token = app.globalData.token;
                    var params = {
                        author: that.data.userInfo.nickName,
                        authorUrl: "https://github.com/aquanlerou/WeHalo",
                        content: that.data.CommentContent,
                        email: "aquanlerou@eunji.cn",
                        parentId: 0,
                        postId: that.data.postId,
                    };
                    //@todo 网络请求API数据
                    request.requestPostApi(urlPostList, token, params, this, this.successSendComment, this.failSendComment);
                } else {
                    wx.showToast({
                        title: '请注意言论！',
                        icon: 'none',
                        duration: 2000
                    })
                    that.setData({
                        commentValue: "",
                        CommentContent: undefined
                    })
                }
            })
        }
    },

    CommentSubmitTips: function () {
        wx.showToast({
            title: this.data.LastTime + "s 后再次评论",
            icon: 'none',
            duration: 1000
        })
    },

    Likes: function () {
        wx.showToast({
            title: "文章点赞功能开发中...",
            icon: 'none',
            duration: 2000
        })
    },


    successSendComment: function (res, selfObj) {
        var that = this;
        that.setData({
            commentValue: "",
            CommentContent: undefined
        })
        wx.showToast({
            title: '感谢你的评论与支持！',
            icon: 'none',
            duration: 2000
        })
        var token = app.globalData.token;
        var urlContent = app.globalData.url + '/api/content/posts/' + that.data.postId;
        var urlComments = urlContent + '/comments/list_view';
        var params = {};
        request.requestGetApi(urlComments, token, params, this, this.successComment, this.failComment);
    },

    failSendComment: function (res, selfObj) {
        console.error('failComment', res)
    },

    /**
     * 评论开关按钮回调
     */
    successSwitch: function (res, selfObj) {
        var that = this;
        that.setData({
            CommentSwitch: !res.data,
        });
    },
    failSwitch: function (res, selfObj) {
        console.error('failSwitch', res)
    },

    open(e) {
        console.log(e.currentTarget.dataset.text);
        wx.setClipboardData({ //复制文本
            data: e.currentTarget.dataset.text,
            success: function (res) {
                wx.getClipboardData({ //获取复制文本
                    success: function (res) {
                        wx.showToast({
                            title: '复制成功',
                            icon: "none", //是否需要icon
                            mask: "true" //是否设置点击蒙版，防止点击穿透
                        })
                    }
                })
            }
        })
    },

    getUserProfile: function () {
        var that = this
        wx.getUserProfile({
            desc: '用于完善用户资料',
            success: (res) => {
                if (res.errMsg == "getUserProfile:ok") {
                    wx.setStorageSync('userInfo', res.userInfo)
                    that.setData({
                        userInfo: res.userInfo,
                        hasUserInfo: true,
                    })
                }
            },
            fail: err => {
                wx.showToast({
                    title: '授权后才能评论哦',
                    icon: 'none',
                    duration: 3000
                })
            },
        })
    },
    toHome() {
        wx.reLaunch({
            url: '/pages/index/index',
        })
    },

    NavChange(e) {
        console.log('NavChange ' + e.currentTarget.dataset.cur);
        var pageCur = e.currentTarget.dataset.cur;
        this.setData({
            PageCur: pageCur
        })

        if (pageCur.indexOf('jiaomao') > -1) {
            wx.reLaunch({
                url: '/pages/index/index'
            })
        };

        if (pageCur.indexOf('wechatApplet') > -1) {
            wx.navigateTo({
                url: '/pages/post/post?postId=47'
            })
        };

        if (pageCur.indexOf('wechatAcc') > -1) {
            wx.navigateTo({
                url: '/pages/post/post?postId=46'
            })
        };

        if (pageCur.indexOf('zhihu') > -1) {
            wx.navigateTo({
                url: '/pages/post/post?postId=49'
            })
        };

        if (pageCur.indexOf('douyin') > -1) {
            wx.navigateTo({
                url: '/pages/post/post?postId=48'
            })
        };
    },

})